# Generated by Django 5.2.8 on 2025-11-24 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTokenBlacklist',
            fields=[
                ('jti', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('client_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('client_secret_hash', models.CharField(max_length=256)),
                ('redirect_uris', models.TextField()),
                ('grant_types', models.TextField()),
                ('response_types', models.TextField()),
                ('scope', models.TextField()),
                ('client_name', models.CharField(max_length=150)),
                ('is_confidential', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('redirect_uri', models.TextField()),
                ('scope', models.TextField()),
                ('code_challenge', models.CharField(blank=True, max_length=256, null=True)),
                ('code_challenge_method', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssoAuthServer.authuser')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssoAuthServer.oauthclient')),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('token', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssoAuthServer.oauthclient')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssoAuthServer.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssoAuthServer.authuser')),
            ],
        ),
    ]
