# Generated by Django 5.2.8 on 2025-11-24 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssoAuthServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstokenblacklist',
            name='jti',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accesstokenblacklist',
            name='revoked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='authcode',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to='ssoAuthServer.oauthclient'),
        ),
        migrations.AlterField(
            model_name='authcode',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='authcode',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to='ssoAuthServer.authuser'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='oauthclient',
            name='grant_types',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='oauthclient',
            name='redirect_uris',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='oauthclient',
            name='response_types',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='ssoAuthServer.oauthclient'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='revoked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='ssoAuthServer.authuser'),
        ),
        migrations.AlterField(
            model_name='session',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ssoAuthServer.authuser'),
        ),
        migrations.AddIndex(
            model_name='authcode',
            index=models.Index(fields=['expires_at', 'user_id'], name='auth_code_expires_c61593_idx'),
        ),
        migrations.AlterModelTable(
            name='accesstokenblacklist',
            table='access_token_blacklist',
        ),
        migrations.AlterModelTable(
            name='authcode',
            table='auth_code',
        ),
        migrations.AlterModelTable(
            name='authuser',
            table='sso_auth_user',
        ),
        migrations.AlterModelTable(
            name='oauthclient',
            table='oauth_client',
        ),
        migrations.AlterModelTable(
            name='refreshtoken',
            table='refresh_token',
        ),
        migrations.AlterModelTable(
            name='session',
            table='session',
        ),
    ]
