# Generated by Django 5.2.8 on 2025-11-25 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssoAuthServer', '0002_alter_accesstokenblacklist_jti_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuser',
            table='ssoAuthServer_authuser',
        ),
    ]
