# Generated by Django 5.2.8 on 2025-11-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssoAuthServer', '0003_alter_authuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oauthclient',
            table='ssoAuthServer_oauthclient',
        ),
    ]
