# Generated by Django 5.2.8 on 2025-11-25 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssoAuthServer', '0004_alter_oauthclient_table'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='authcode',
            new_name='ssoAuthServ_expires_00eaa8_idx',
            old_name='auth_code_expires_c61593_idx',
        ),
        migrations.AlterModelTable(
            name='authcode',
            table='ssoAuthServer_oauthcode',
        ),
    ]
